### ISSUE TITLE
Add and use classification information

### ISSUE THREAD

**Issue by LinguList** [digling/edictor#100]
It seems that in some situations, classification information may be useful to be in the edictor and also be used there. I tend to display this as another column indicating classification. But where to use this as an additional features is still unclear. Maybe in cognate sets and alignments, where one might want to only work on one set before.

Maybe also in the seleciton, where one might want to filter languages from one sub-branch.

This would also avoid issues like #99 as they are clearly due to the attempt to capture classification in the doculect identifier, which is not necessarily recommended.

**Comment by Anaphory** [comment]
The issue that led to us constructing long names and noticing #99 (which is officially about something else) is that the Cognateset pseudowindow does not show the fundamental classification column of families, otherwise we would have used/abused the Family column there (and added region information into that, incl. if necessary numerical IDs to sort by)

**Comment by LinguList** [comment]
I agree, and I know that other scholars would like the same feature. the problem is that we'll be forced to introduce a new layer of uncertainty and a procedure to react on it: if there's no family annotation, as in many other applications of the edictor, we need to check whether the column exists or not. I guess, this is handable as just another if-statement, but it would be cool to decide in a principled way how to display subgrouping information. So I suppose we discuss this in this thread (as I see this more long-term), while #99 can be solved quickly by just using fixed cell size with the ... for too long cells, as given by css/html. I'd like to also hear the opinion of @thiagochacon on this matter, especially WHERE the classification would be useful, to handle it properly. I'd assume we have families encoded in a simple way, say "subgroup, subsubgroup, ....", or is there reason to do it otherwise?

**Comment by Anaphory** [comment]
In our case, we wanted to sort – and have visibly present – by regional information, ordered clockwise around the Savu sea, and then by family, because that gives a good prior for where language contact may lead to possibly difficult-to-recognize cognates. Just to give you another use case.

**Comment by LinguList** [comment]
I would generally start inside smaller families to annotate cognates and
then search for signal across families. Here, sorting is less important
but only looking at one language group at once. For this, one can select
a soubgroup at the moment, and only work on that part. What IS missing
is the information of sugroups in the language selection drop-down list,
which exacerbates finding those varieties one wants to look at. I can
imagine having group information present in this case to allow for a
quick subselection. Once major cognates are assigned, sorting will
matter less, as one should see the large groups already (but having
family information in another column sees possible and useful).

I was also thinking: one could remove classification information in the
cell display but have it as string underlyingly, like "[Germanic]
English", which is as well easy to implement, and would not affect
searching. But I'd still prefer to keep different info in different columns.

**Comment by thiagochacon** [comment]
I agree that info about linguistic families and perhaps also regions would be helpful for working with large datasets. if we think of edictor as a potential future database (not only a tool for analyzing the data), it makes sense that this sort of information be in a proper column.

**Comment by LinguList** [comment]
ordering of data is now supported, so you can order your taxa in a convenient way and sort in the cognates module. I think this should be sufficient for now.
