### ISSUE TITLE
Edictor seems to remove unfamiliar columns

### ISSUE THREAD

**Issue by Anaphory** [digling/edictor#101]
This is only a fast observation that may not be true, but I noticed that a `tsv` file someone got out of edictor did not have a “source” column. It may be that I provided them with a file without `source`, I need to check, but otherwise:

If Edictor removes columns that it does not know, that is bad, because we (and I assume it's a common pattern) aggregate the files we edit in edictor from separate source files and would like to feed alignments etc. back to these files. It would therefore be appreciated if colums, such as “which file was this row taken from”, were kept.

**Comment by Anaphory** [comment]
I appreciate that this requires some thought on how to fill columns when new words are added through the edictor interface.

**Comment by LinguList** [comment]
column reduction was disapproved from an older version. Before, only visible columns were saved. Now, the only reason for not exporting a column when saving I can think of is that the original data had not enough tab-stops. If tab-stop number not matches the number of columns exactly, this will have bad effects. It may work, but usually it doesn't work at all. I don't have any sympathy to relaxing that behaviour, as one should feed proper tsv-files, and things can easily be shifted with empty cells, but I think that the routine of loading tsv-files needs to be enhanced, by properly checking (thinking of github's explicit error messages when loading bad tsv).

**Comment by LinguList** [comment]
closing for now, please re-open if there's a toy example to trigger the bug.
