### ISSUE TITLE
image export from alignments of a cognate set

### ISSUE THREAD

**Issue by thiagochacon** [digling/edictor#104]
when editing a set of cognate tokens, we can export a tab file, but it would be also be good to be able to export an image file from the alignements of a particular cogid set as well, quite handy for publications and presentations.

**Comment by LinguList** [comment]
Yes, I also occasionally use figures from those things, also the shared morpheme network. There are, however, already good workarounds which one can use:

For firefox, for example, there are plenty of extensions that handle screenshotting the things in the browser window.

Same applies to Chrome.

What I use on firefox is the possibility to debug the source code and screenshot only the element, like the alignment. This is much cleaner, better quality, and avoids that one needs to post-edit. There should also be addons on firefox to handle this within an addon (I'd search for "node screenshot", or "html element screenshot").

I'll consider, when I have time, to handle this from within the app, as I also found on [this link](http://stackoverflow.com/questions/6887183/how-to-take-screen-shot-of-a-div-with-javascript), that there is an addon that allows to do this.

**Comment by LinguList** [comment]
okay, too complicated,
