### ISSUE TITLE
TSV-Format: Increase verbosity in Errors and use specific library for parsing

### ISSUE THREAD

**Issue by Anaphory** [digling/edictor#105]
I just tried to load a (huge! 27071 rows with 27 columns) tsv file into edictor.

The red “Open the file” <div> is shown, but nothing happens when clicking it.

The error console says:
11:18:59.240 TypeError: data is undefined
csvToArrays() wordlist.js:206
showWLS() wordlist.js:523
onclick() edictor.digling.org:1

The small context of the line throwing the error is

```
  /* get the header */
  var header = [];
  for (j = 0; j < data.length; j++) {
    var datum = data[j].toUpperCase();
```

Is this an expected result of loading a file that is too big for edictor to handle, or is this an expected result of a mal-formed tsv file (could be, I did some manual fiddling with it to merge edits from two sources) or is this unexpected behaviour that should at least raise an explicit error message?

**Comment by Anaphory** [comment]
Okay, taking only the top 50 lines of the huge file gives the same result.

**Comment by LinguList** [comment]
It seems like malformed tsv. We need much better checks for this, ideally switching to some external library fro reading tsv. There are plenty now in JS.

**Comment by Anaphory** [comment]
Does ID have to be the first column in the file?

**Comment by Anaphory** [comment]
Yes, it does, and that's the only edit I needed to make.

**Comment by LinguList** [comment]
I'll convert this issue in the title. We need better direct feedback ("your data is not tsv"), and using a parser rather than the current format is also important.

**Comment by Anaphory** [comment]
Remark: Note that the file I originally tried it with *was* tsv, just not *with a numerical ID column named ID as first column*. (There was a column named `ID`, and the first column had an empty name as was a numerical ID column.)

**Comment by LinguList** [comment]
yep, I got that. I think, having ID in column one is something I want to maintain, as it is just good style. But it should be properly documented.

**Comment by LinguList** [comment]
yep.

**Comment by LinguList** [comment]
I think, parsing has be somewhat enhanced by now, and users should generally stick to files which are ideally produced using the template module, or copy-pasted from their excel to plain text (where you have automatically the number of text required). It is up to a general documentation to account for this, and the current debugging should be okay enough for the moment,
