### ISSUE TITLE
Drop-Down Menu in Partials frame is not initialized

### ISSUE THREAD

**Issue by Anaphory** [digling/edictor#106]
I read enough documentation to get the Partials window to show me something reasonable (and I actually looked into the source code to use the `>>` hack), but I don't know the reformatting magic and the backend to tell you what I'm doing wrong, why 

![edictor-bug](https://cloud.githubusercontent.com/assets/1579723/19775935/7d0ddcd8-9c72-11e6-8eaf-060d43f705e4.png)

shows a gray “None selected” drop-down menu with no content instead of the blue menus I'm used to in other places in Edictor. (And I notice that there is only one such drop-down menu, but you know how huge our word list is, so of course I would love one for for doculects and one for meanings in there, or some other way of reducing the amount of these that we see on the screen.)

**Comment by Anaphory** [comment]
It looks like it *is* initialized and shows concepts (not morphemes, as I might have thought) when the MORPHEMES column exists. (Or I changed something else, as well, but I don't think so.)

Is that possible and intended?

**Comment by Anaphory** [comment]
This time I didn't add the “Morphemes” column, but it worked fine after

 -  `$COGID>>COGID`
 - open SETTINGS frame
 - do a null-edit
 - click the “reload” in settings
 - open PARTIAL COGNATE SETS editor frame

**Comment by LinguList** [comment]
Just had the same bug when working on a new dataset. Apparently, it is a
conflict between the two cognate modules? I assume, partial cognates are
best to edit if one has a column called "cogids" which is prefilled with
zeros for each morpheme in the data.

But whether this relates to the problem you mention is not clear. I need
to investigate the bug more closely, once I manage to trigger it again.

**Comment by Anaphory** [comment]
Oh, there is interaction between the two cognate modules? I thought they were entirely separate.

But now that you mention it, it *may* be that the other times when it didn't work I opened the COGNATE SETS editor frame before doing steps like the ones above.
