### ISSUE TITLE
Always show active concepts

### ISSUE THREAD

**Issue by Anaphory** [digling/edictor#115]
In the “Select Concept” dropdown in the “Edit and align cognate sets:” pseudo-window, it would be nice if the currently active concept(s) were always shown, even when the filter is active. That would make de-selecting them and jumping between concepts a lot easier.

**Comment by LinguList** [comment]
I'm in general not fond of the selector there, but I wanted to stick to
some unifying design. Changing that behavior will be a bit tricky, as it
is already tricky to hack into the current script (I use a multiselect
library) to get the behavior needed. I agree that it might make one's
life easier if one works cross-semantically...

**Comment by Anaphory** [comment]
It's actually less about the working cross-semantically, it's about the post-completion error of
“I want to look at meaning X now” – types X in the filter – selects X – clicks “OK” – notices that Y is still in there, so has to go back to typing Y in there to uselect; *and now* the chance of that error is even bigger, because now the selector shows Y, not X, which is active, by default.

**Comment by LinguList** [comment]
ah, I just found this: if you always show active concepts, you can't filter the data anymore if you have selected all concepts, so the filter will be useless, so this goes against the whole logic of the filter. I added another feature, namely that you can now similarly to the cognate sets panel, just switch meaning by meaning through the wordlist data. I think this is pretty convenient, and it may help if you want to sieve through different sets (assumes the order of the meanings, which is alphabetical).
