### ISSUE TITLE
Combining classes logic has changed

### ISSUE THREAD

**Issue by Anaphory** [digling/edictor#127]
The logic on combining cognate classes has changed. Before, combining

    L1  | C1 |  form |  1  [X]
    L2  | C1 |  form |  1  [ ]
    L3  | C1 |  form |  2  [X]
    L4  | C1 |  form |  2  [ ]
would give

    L1  | C1 |  form |  1  [ ]
    L2  | C1 |  form |  1  [ ]
    L3  | C1 |  form |  1  [ ]
    L4  | C1 |  form |  1  [ ]
Now it gives

    L2  | C1 |  form |  1  [ ]
    L1  | C1 |  form |  2  [ ]
    L3  | C1 |  form |  2  [ ]
    L4  | C1 |  form |  2  [ ]

(or moves L3 to Class 1 instead, without apparent logic.)
Git bisect might help.

**Comment by LinguList** [comment]
I cannot replicate this! Please provide a snippet of data, so I can check with it. There must be something else hidden which was not foreseen. To my best knowledge, the behavior has not changed since.

**Comment by LinguList** [comment]
still cannot replicate the issue, please name your browser, and re-open if it persists...

**Comment by Anaphory** [comment]
I could not reproduce this any more two days ago, either. No idea what had been going on there – but I think I had the same behaviour in qutebrowser (QtWebEngine-based) and Firefox, because using a strange browser like that, that was the first thing I checked.

**Comment by LinguList** [comment]
just reopen when it re-appears. It is much likely that some browsers will have a different behaviour, as the merge procedure is not easy to implement (and it almost knocked me out when I first programmed it).
