### ISSUE TITLE
Edictor freezing/crashing browser

### ISSUE THREAD

**Issue by IndianaTones** [digling/edictor#136]
Open in Edictor 
[D_dogon-aligned_ED-2.txt](https://github.com/digling/edictor/files/1453957/D_dogon-aligned_ED-2.txt)
Select Alignment column 
FREEZE/CRASH (different computers, different browsers)

**Comment by LinguList** [comment]
[dogon.tsv.txt](https://github.com/digling/edictor/files/1454077/dogon.tsv.txt)

you need to remove the "" symbols. In your export from excel, you have two options: field separator ({TAB}) and the text-delimiter, which you don't need. I removed it, and it works.

**Comment by LinguList** [comment]
this could be handled by removing all "" characters from file input. Maybe I should do this, for the meantime, please make sure you set the text-delimiter to nothing.

**Comment by LinguList** [comment]
here's some info: https://support.office.com/en-us/article/Text-Import-Wizard-c5b02af6-fda1-4440-899f-f78bafe41857

I'm no good in excel, as I use linux, but the ideas are the same here.

**Comment by IndianaTones** [comment]
Works!!!
