### ISSUE TITLE
adding proto-forms, a new approach

### ISSUE THREAD

**Issue by LinguList** [digling/edictor#142]
If users open the cognate panel (Analyze -> Cognate sets), it would be convenient to add proto-forms just as we add a new language. The difference is:

1 proto-forms should have a form (segments/tokens)
2 proto-forms should have the cognate id they have in the very column

These modifications will make it easy to handle. For partial cognates, we will add proto-forms morpheme by morpheme, as lexical reconstruction is an additional step.

**Comment by thiagochacon** [comment]
this also relates to issue #157

**Comment by LinguList** [comment]
Yes, but since #157 is already solved, it is easier to build on this one...
