### ISSUE TITLE
Add, delete and change information to the file within Edictor

### ISSUE THREAD

**Issue by thiagochacon** [digling/edictor#157]
For several reasons it is convenient and more consistent to be able to add and change information to a dataset in Edictor. 

Currently one can change information from any column by typing, which is great, but one cannot delete a row nor add a new one. 

For instance, one may want to add a new language, with new data, or make reconstructions to proto-languages or intermediate proto-languages. In all these cases, new rows will have to be created and new information added.  

Maybe there could be an interface to add or delete rows in EDIT > WORDLIST and  EDIT > COGNATE SETS

**Comment by LinguList** [comment]
You CAN add rows and delete them. Click for this on the ID cell at the left, a pop-up will allow you to do something. There is just one restriction: if you add a new language, it won't show up in the panel that allows you to filter, so you need to download and reload the file. But this is a design feature, as it would cost too much time and code to re-calculate those basic statistics.
