### ISSUE TITLE
Partial cognates with less than 2 phonemes

### ISSUE THREAD

**Issue by Schweikhard** [digling/edictor#158]
In Edit Partial Cognate Sets, morphemes which consist of only one phoneme can't be added to a COGID by clicking on them and then on the COGID's column header. It needs to be done manually instead via the Wordlist (or in an editor).
In my test database for Germanic, there are a lot of inflectional endings which I wanted to group together under COGIDs and which only consist of a single vowel.

The bug persists when trying it in different browsers or on different computers.

**Comment by LinguList** [comment]
could you paste a short example file here? add the ending `.txt` to it, so you can upload it on github. It is easier to understand when having a toy example, also to figure out whether it's a bug or a problem of data handling.

**Comment by Schweikhard** [comment]
Sure, just adding my general example file as it's not very long.
[GermanicExamples.txt](https://github.com/digling/edictor/files/1932192/GermanicExamples.txt)

**Comment by LinguList** [comment]
Okay, bug confirmed. Thanks for spotting this. Will take some time before I can solve this, unfortunately, as I'll need to dig into the code. But this is a true bug: if you add another sound, it works, if you have only one sound in a morpheme, it doesn't work. Annoying...

**Comment by LinguList** [comment]
I close this now. The partial cognate editing panel is something I would anyway discourage by now.
