### ISSUE TITLE
Sorting in the correspondence patterns pane

### ISSUE THREAD

**Issue by Mo-tero** [digling/edictor#164]
Is it possible to add more sorting functions in the correspondence patterns pane? 
This would be a sorting function similar to the Wordlist sort function (e.g by clicking on column headers or by a different method). 
This would allow sorting by a particular sound in a particular language in a given pattern set for instance. Also, within a set, it would be helpful to line up those with the same index (e.g. sort by all initial sounds etc.)
Another possible feature may be a "show all" button in which all of the words in a set would be revealed or all of the words in all of the sets could be revealed. As it stands now, one must click on either the cogID to see the full set (in a small window, which must then be closed before continuing) or by clicking on each sound to reveal the word. A "show all" function would be a quick way to look at environments after sorting by indexes for example.

**Comment by LinguList** [comment]
With the new selection mechanism for correspondence patterns, this would be available now.
