### ISSUE TITLE
Alignment algorithm gives very suboptimal results

### ISSUE THREAD

**Issue by Anaphory** [digling/edictor#182]
Has the built-in multi-aligner inside Edictor aways done strange things like this?
![2021-05-20-124639_2560x1440_scrot](https://user-images.githubusercontent.com/1579723/118966246-d1f2ff80-b969-11eb-95cd-3aadd859c8ff.png)
I know there's better alignment methodology in LingPy, but this alignment of `l` with `o` instead of in that big chunk of `l` in the middle column really surprised me.

If I encouter a thing like this, is there a quick way to edit this alignment to one where all `l`s are aligned?

**Comment by LinguList** [comment]
This is the column editing function. Press on language labels, and you can then edit them SYNCHRONICALLY. So you select those languages which you wan to edit b the same operation.

**Comment by LinguList** [comment]
And no idea why it aligns vowels and consonants, sorry, but since the alignment itself is helpful enough to start, I think it is not worth to dig into this more, but thanks for sharing.
