### ISSUE TITLE
Upload doesn't succeed

### ISSUE THREAD

**Issue by martino-vic** [digling/edictor#187]
I'm trying to upload [this file](https://github.com/martino-vic/ronatasbertawot/blob/main/cldf/forms.csv) through the edictor online tool. A big read button "Open the file." appears but nothing happens if I press it. I wonder if my data is just too big (~1800 rows) or if it's the wrong type of file I'm inputting or if it's something else.

Related issues:
- https://github.com/lingpy/pyedictor/issues/3 
- https://github.com/martino-vic/ronatasbertawot/issues/3#issuecomment-1079646083

**Comment by LinguList** [comment]
You need pyedictor first, obviously.

**Comment by LinguList** [comment]
EDICTOR does not allow to use CSV, it must be TSV. And column names are different from CLDF.

**Comment by LinguList** [comment]
[dummy.tsv.zip](https://github.com/digling/edictor/files/8886706/dummy.tsv.zip)

This file (unzipped) works.

**Comment by LinguList** [comment]
Created with `edictor wordlist` in the ronatasbertawot.

**Comment by martino-vic** [comment]
Ah okay, now I understand it, thanks, misunderstood the workflow
