### ISSUE TITLE
Grouping sounds not carried over to Alignments

### ISSUE THREAD

**Issue by Tarotis** [digling/edictor#190]
I am currently facing the problem that sometimes, the grouping of sounds does not get carried over to the alignments tab. Instead, I have to confirm the grouping a second time so it doesn't get lost. Similarly, even in the main view, segmenting with "+" does not always get carried over and often needs a second confirmation.

Two possible explanations:

- The writing of the data is disturbed on my or the server's side, and the change get's displayed without actually being saved
- Some problem in the connection to the Alignments, similarly to #188 

Now that I am aware of it, I am just entering the change two times to avoid further problems.

**Comment by LinguList** [comment]
Facing the same problem.

**Comment by LinguList** [comment]
What happens is that if you group a sound, it ONLY goes over to the alignment tab if you go with cursor down or up. Somehow, the ENTER does not trigger it anymore. Unfortunately, it is difficult for me to now look into this in EDICTOR, as this is quite tedious to debug.

**Comment by LinguList** [comment]
But I am also annoyed by it.

**Comment by LinguList** [comment]
This issue is related to the one in #192. We can close one of the two.
