### ISSUE TITLE
Can't add alignments on local server

### ISSUE THREAD

**Issue by FredericBlum** [digling/edictor#225]
@LinguList I am trying to run local servers for teaching and have troubles modifying the alignments locally. To reproduce:

1. Clone my [workshop template](https://github.com/FredericBlum/workshop_template).
2. cd to `passau/edictor', where the SQLite and the config.json are saved
3. run `edictor server` and open any of the six available databases
4. Select any cognate set and submit new alignments

I can do all other kind of changes (renumber cognate sets, change tokens, etc), but I cannot work with the alignments.

**Comment by LinguList** [comment]
Looking into this now. It turns out. The alignment is stored, but the program hangs, if you modify an alignment. This is something I hope to be able to fix in a couple of minutes now.

**Comment by LinguList** [comment]
For my own documentation, the error code:

```
Uncaught TypeError: WLS.column_names[WLS.header[jdx]] is undefined
    storeModification http://localhost:9999/js/wordlist.js:1575
    recheck http://localhost:9999/js/patterns.js:1348
    storeAlignment http://localhost:9999/js/wordlist.js:2810
    onclick http://localhost:9999/edictor.html?file=calc&remote_dbase=calc&doculects=Kaluli|Beami|Onabasulu|Jasya&columns=DOCULECT|FAMILY|CONCEPT|FORM|TOKENS|COGID|ALIGNMENT|PATTERNS|NOTE#settings_anchor:1
```

**Comment by LinguList** [comment]
Problem is that the patterns are also updated, but they are empty. As a result, if one touches the alignment, the method tries to update the patterns, but them being empty means that this throws an error.

**Comment by LinguList** [comment]
The fix I added is okay(ish). More issues may result. Problem in general is the interplay between alignments on the one hand and then updating patterns o the other hand.
