### ISSUE TITLE
pip install edictor[lingpy] not working on Mac

### ISSUE THREAD

**Issue by FredericBlum** [digling/edictor#226]
@LinguList @patkaiist As tried on different computers, the command `pip install edictor[lingpy]` mentioned in the README does not seem to work on Mac. The packages need to be installed individually. 

```shell
(test) blum@lingn45w Projects % pip install edictor[lingpy]
zsh: no matches found: edictor[lingpy]
```

Is the following list of dependencies correct?

- lingpy
- lexibase
- edictor
- lingrex

or am I missing a package? I can then adapt the description and open a PR.

**Comment by LinguList** [comment]
So the brackets don't work on a mac. That is unfortunate. Do we have a description of this anywhere on the internet, to confirm that it is a mac problem? I mean, it is probably a problem of Mac plus the system you use for virtual envs, right?

**Comment by FredericBlum** [comment]
Haven't found any details on that, but I did find that when using '', it works! The following two options are feasible:

```shell
pip install 'edictor[lingpy]'
pip install "edictor[lingpy]"
```

if those also work on other operating systems, we might just add this instead of installing individually.

**Comment by LinguList** [comment]
Super, it works. So it is a terminal emulator problem I guess. If you prepare a PR, where you maybe take `"edictor[lingpy]"` as the default and say (on many terminals, it also works if you type `edictor[lingpy]` without the quotation marks), then we are fine!
