### ISSUE TITLE
MacOS needs a virtualenv for EDICTOR to run

### ISSUE THREAD

**Issue by FredericBlum** [digling/edictor#228]
@LinguList @patkaiist Even though it is intended to use a venv anyway, we might want to make the need for this explicit. If running `edictor server` without, one receives the following error message:

```shell
$ python -m edictor server
No module named edictor.__main__; 'edictor' is a package and cannot be directly executed
```

So we need to implement a venv in all cases:

```shell
python3 -m pip install virtualenv
python3 -m venv venv/edictor
source venv/edictor/bin/activate
pip install 'edictor[lingpy]'
edictor server
```

If you agree, I update the ReadMe accordingly to make some more propaganda for the use of venv's.

**Comment by LinguList** [comment]
On linux, it is no longer possible to install packages without using a 
venv now. Adding instructions for mac users is a good idea. This 
complements the instructions for windows users then!
