### ISSUE TITLE
Alignments not refreshing after being edited

### ISSUE THREAD

**Issue by thiagochacon** [digling/edictor#63]
When doing alignments (in the alignment pop up window) the data is submitted and EDICTOR says the data was saved, however no apparent change has happened in "alignment" itslef (i.e. in the alignment column, not in the alignment pop up window). It is only after refreshing the browser window that the changes appear in the actual alignment column.

**Comment by LinguList** [comment]
the question that needs to be decided is whether this is a desired feature or not. Refreshiing may cost time, and we often do not want to refresh the wordlist panel. In the cognates panel, however, refreshing would be useful. I'll have to think about this.
