### ISSUE TITLE
edictor doesn't store (problem with URLS in edictor)

### ISSUE THREAD

**Issue by LinguList** [digling/edictor#65]
use huber1992 [http://tsv.lingpy.org/?file=huber1992&remote_dbase=huber1992#cognates_anchor](http://tsv.lingpy.org/?file=huber1992&remote_dbase=huber1992#cognates_anchor) to replicate and edit "bird", two clusters around "piti" etc. There's an error message, but not clear why.

**Comment by LinguList** [comment]
it is clear now: the message is there because the url passed to the server is too long.

We need a general idea how to handle urls, either switching to post-statements, or switching to some compressed version, as is used in the [json editor example](http://jeremydorn.com/json-editor/).

**Comment by thiagochacon** [comment]
I have reported problem related to clustering more than 10 or so languages in a single COGID. The problem was that EDICTOR would give me an erro message, saying the data could be stored. 

I have now found a "solution" for that. Whenever we face this problem, it is possible to just create a new cognate id for the whole set of related forms. So the problem is actually with COMBINE old COGID forms, but NEW is ok.

This is a partial solution that can work when one is editing a whole dataset. However, that could bring problems when one is dealing with a subset of languages from that dataset.

**Comment by LinguList** [comment]
Thanks for the update. This is interesting and important to trace the bug down. I still think the most likely solution is the length of the data that is submitted at once, so I need to change the submission practice (from "get" to "post"). 

Generally, both routines, the "new cogid" and the "combine" are dangerous, since combination picks the smaller cogid of two or more, so combination will also not work on the full dataset if you have only loaded a part. 

As a general practice for working with parts of the data when also considering the global level, it may be important to just load the full data and specify afterwards only a part of the data to be worked with (using the buttons in the menu). In this case, changes will be made globally, but one still only looks at parts of the data. 

For cases where one wants to work on smaller subsets, we may consider adding an additional layer of cogids (name is arbitrary, but it should end witn -id): then, in the end, there will be different layers of cogids for small groups and the whole data. This is potentially also what one would do in classical linguistics: starting with one group, working up the things, and then searching for cognates across groups.

Let me know if you fancy this small-group-big-group solution with two type of cogids. I can rather quickly adjust it and add another column.

**Comment by LinguList** [comment]
As a general point to solve this, the edictor needs to switch from "get"-statements to "post" statements, both in the settings file and in the direct application. This will mean that the user can't simply create a quick URL from scratch, but it is much saver to guarantee that all data is consistently stored.

**Comment by LinguList** [comment]
addon: generally switching to post in submitting data seems possible, avoiding long urls is impossible, since we pass the to JS and JS can't handle post-requests.

**Comment by LinguList** [comment]
This issue may be solved when switching to the solution with lzw-compression mentioned in #91 
The question is, however, whether we need to have this already with version 1.0, given that it needs to be included at quite a few different points:

* server code
* js code

and we need to make sure that it works identical in JS and python.
