### ISSUE TITLE
huber database won't allow navigation

### ISSUE THREAD

**Issue by thiagochacon** [digling/edictor#93]
After updates on the Edictor, Hbuber database has behaved oddly. It may launch, or may not launch, and if it does, it does let the user to do anything with it. I click in every possible clickable field and nothing happens.

**Comment by thiagochacon** [comment]
actually, it allows me to save and download the database, but does not allow any navigation in the browser. I have updated and used chrome and firefox.

**Comment by LinguList** [comment]
problem is not necessarily the update, but my server, who does not allow
URLs with lines which are too long, which is a problem for the concepts,
I guess.

I just tested with normal settings, using this URL:

http://tsv.lingpy.org/?remote_dbase=huber1992.sqlite3&file=huber1992&css=menu:show|textfields:hide|database:hide|&preview=10&basics=DOCULECT|CONCEPT|IPA|COGID|ALIGNMENT&pinyin=CHINESE&sampa=IPA|TOKENS&highlight=TOKENS|ALIGNMENT

and it worked without problem

Did you use another URL, with selected concepts or the like, which was
longer?

this one, where I only choose a subset of languages, also works:

http://tsv.lingpy.org/?remote_dbase=huber1992.sqlite3&file=huber1992&css=menu:show|textfields:hide|database:hide|&preview=10&basics=DOCULECT|CONCEPT|IPA|COGID|ALIGNMENT&pinyin=CHINESE&sampa=IPA|TOKENS&highlight=TOKENS|ALIGNMENT&doculects=awa|baniva|barasana|bar%C3%A1%7Cbar%C3%AD%7Cbora|cabiyar%C3%AD%7Ccarapana|carijona|cat%C3%ADo|cha%27palaachi|chimila|cubeo|cuiba|curripaco|desano|d%C3%AD%CC%B5mi%CC%B5na|embera%20Dari%C3%A9n|embera%20Tad%C3%B3%7Cembera%20cham%C3%AD%7Cepena%20Saija|epena%20basurud%C3%B3%7Cgiacone|guahibo|guambiano|guayabero|ika|inga|jitnu|jupda|kakua|kams%C3%A1%7Ckogui|koreguaje|macuna|mira%C3%B1a|muinane|nukak|ocaina|orej%C3%B3n|piapoco|piratapuyo|playero|puinave|p%C3%A1ez|res%C3%ADgaro|secoya|siona|siriano|s%C3%A1liba|tanimuca|tariano|tatuyo|totor%C3%B3%7Ctsafiqui%20pila|tucano|tunebo%20central|tuyuca|waimaja|wanano|wayuu|witoto%20mi%CC%B5ni%CC%B5ca|witoto%20murui|witoto%20ni%CC%B5pode|wounaan|yucuna|yukpa|yurut%C3%AD

My provider restricts URLs which are too long, and this is what I
suspect may happen in certain cases, but please paste your URL to
confirm my suspicion.

**Comment by thiagochacon** [comment]
Well, I have always been using the same URL, as I have it bookmarked in my browser.

I tested the same URL you did in Firefox and Chrome. I have experiences limitations any way. 

Is there any other kind of update I need to do with my browser regarding the new version of Edictor?

Thiago Costa Chacon
Linguista – Professor Adjunto
Departamento de Linguística, Português e Línguas Clássicas
Universidade de Brasília


Date: Sun, 24 Jul 2016 01:15:50 -0700

**Comment by LinguList** [comment]
I'll later the day test on firefox-mac and chrome-mac and safari-mac. So
far, it works on firefox-linux and chrome-linux for me, but could you,
in the meantime, send one or two screenshots, so that I can compare it
with what I see? you can attach now images to posts on github, which is
quite convenient for our case...

**Comment by thiagochacon** [comment]
Here are the setps I have been following:

1. Opening bookmark:
http://tsv.lingpy.org/?file=huber1992&remote_dbase=huber1992&columns=DOCULECT|CONCEPT|COUNTERPART|TOKENS|ALIGNMENT|COGID&basics=DOCULECT|CONCEPT|COUNTERPART|TOKENS|ALIGNMENT|COGID&formatter=COGID

2. Edictor tries to launch it but never accomplishes: you can see the wordlists but it win't click. A "loading" icon appears

In Firefox it does not work, but now it does in Chrome (I don't know why).  

Thiago Costa Chacon
Linguista – Professor Adjunto
Departamento de Linguística, Português e Línguas Clássicas
Universidade de Brasília


Date: Sun, 24 Jul 2016 23:40:34 -0700

**Comment by LinguList** [comment]
I'm very sorry, but first, the bug repeats with me, and I don't really
know, why.

Strangely, the bug does not always appear, and I think it depends on how
fast the data is transferred from the database to the web-app, which
suggests that in the future, it should better be handled differently.

For me, when I just tried, this link worked, and I guess it is the
safest for the moment:

* http://edictor.digling.org/?file=huber1992&remote_dbase=huber1992

With google crhome, it also worked, and when you use it, I suggest to
open it in incognito-mode, to ensure that google does not save any
settings, which is not the behaviour we want, as it is vivid data that
changes, etc., and should be re-loaded each time one first opens the app...

I won't forget it and later test again on mac and on different browsers...

**Comment by LinguList** [comment]
Okay, found tiem to check on macbook now, and it turnes out, that it works without problems on firefox with the following URL:

* http://tsv.lingpy.org/?remote_dbase=huber1992.sqlite3&file=huber1992&css=menu:show|textfields:hide|database:hide|&formatter=COGID&preview=10&basics=DOCULECT|CONCEPT|IPA|COGID|ALIGNMENT&sampa=IPA|TOKENS&highlight=TOKENS|ALIGNMENT&columns=DOCULECT|CONCEPT|IPA|ALIGNMENT|BORROWING|COGID|COMMENT|COUNTERPART|MORPHEMES|QLCID|SCAID

What may help in getting it work is, as I mentioned before, to use the anonymous mode of firefox, as this prevents that things are implicitly stored (which may disturbe the navigation). Please, @thiagochacon , try this link in anonymous and normal ff and let me know what you get. As to the selection of more languages in advance, I'm not sure, whether I'll get it fixed soon enough, and I'll need to probably re-work on the app for that, which may cost a couple of months. 

Another problem may be the speed of internet connections, which would prevent that the data is being sent out, but this is only a suspicion.
